version: '3.8'

services:
  mysql: # See Also: https://hub.docker.com/_/mysql
    image: mysql:5.7
    hostname: hostname-mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    build: .
    image: payhere-python-project
    volumes:
      - ./src/app:/app/src/app
      - ./wait-for-it.sh:/app/wait-for-it.sh
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    command: |
      sh -c "../wait-for-it.sh mysql:3306 --
             python app/main.py"

